name: enough_mail
description: IMAP, POP3 and SMTP for email developers. Choose between a low level and a high level API for mailing. Parse and generate MIME messages. Discover email settings.
version: 2.1.1
homepage: https://github.com/Enough-Software/enough_mail

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  basic_utils: ^5.5.4
  collection: ^1.17.2
  crypto: ^3.0.3
  encrypt: ^5.0.1
  enough_convert: ^1.6.0
  enough_serialization: ^1.4.0
  event_bus: ^2.0.0
  #intl: ^0.18.1
  intl: ^0.17.0-nullsafety.2
  pointycastle: ^3.7.3
  xml: ">=6.0.0 <7.0.0"

dev_dependencies:
  lints: ^2.0.1
  test: ^1.20.1
  timezone: ^0.9.0
